/*
 * Copyright (c) 2015-2016, Renesas Electronics Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   - Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 *   - Neither the name of Renesas nor the names of its contributors may be
 *     used to endorse or promote products derived from this software without
 *     specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef BL2_PHY_INIT_H__
#define BL2_PHY_INIT_H__

#define	INIT_DRAM_TBL_PHY_START		(0x400U)
#define	INIT_DRAM_TBL_PI_START		(0x200U)

#define	INIT_DRAM_TBL_PHY_3200_NUM	(827U)
#define	INIT_DRAM_TBL_PI_3200_NUM	(181U)

#define	INIT_DRAM_TBL_PHY_1600_NUM	(827U)
#define	INIT_DRAM_TBL_PI_1600_NUM	(181U)

#define	PHY_MAX_NUM			(4U)

enum {
	PHY_DQ_TSEL_SELECT_0 = 0,
	PHY_DQS_TSEL_SELECT_0,
	PHY_LP4_RDLVL_PATT8_0,
	PHY_DQ_SWIZZLING_0,
	PHY_WRLVL_HARD1_DELAY_OBS_0,
	PHY_WRLVL_HARD0_DELAY_OBS_0,
	PHY_CLK_WRDQ1_SLAVE_DELAY_0,
	PHY_CLK_WRDQ0_SLAVE_DELAY_0,
	PHY_CLK_WRDQ3_SLAVE_DELAY_0,
	PHY_CLK_WRDQ2_SLAVE_DELAY_0,
	PHY_CLK_WRDQ5_SLAVE_DELAY_0,
	PHY_CLK_WRDQ4_SLAVE_DELAY_0,
	PHY_CLK_WRDQ7_SLAVE_DELAY_0,
	PHY_CLK_WRDQ6_SLAVE_DELAY_0,
	PHY_CLK_WRDM_SLAVE_DELAY_0,
	PHY_RDDQ1_SLAVE_DELAY_0,
	PHY_RDDQ0_SLAVE_DELAY_0,
	PHY_RDDQ3_SLAVE_DELAY_0,
	PHY_RDDQ2_SLAVE_DELAY_0,
	PHY_RDDQ5_SLAVE_DELAY_0,
	PHY_RDDQ4_SLAVE_DELAY_0,
	PHY_RDDQ7_SLAVE_DELAY_0,
	PHY_RDDQ6_SLAVE_DELAY_0,
	PHY_RDDQS_DQ0_FALL_SLAVE_DELAY_0,
	PHY_RDDQS_DQ0_RISE_SLAVE_DELAY_0,
	PHY_RDDQS_DQ1_FALL_SLAVE_DELAY_0,
	PHY_RDDQS_DQ1_RISE_SLAVE_DELAY_0,
	PHY_RDDQS_DQ2_FALL_SLAVE_DELAY_0,
	PHY_RDDQS_DQ2_RISE_SLAVE_DELAY_0,
	PHY_RDDQS_DQ3_FALL_SLAVE_DELAY_0,
	PHY_RDDQS_DQ3_RISE_SLAVE_DELAY_0,
	PHY_RDDQS_DQ4_FALL_SLAVE_DELAY_0,
	PHY_RDDQS_DQ4_RISE_SLAVE_DELAY_0,
	PHY_RDDQS_DQ5_FALL_SLAVE_DELAY_0,
	PHY_RDDQS_DQ5_RISE_SLAVE_DELAY_0,
	PHY_RDDQS_DQ6_FALL_SLAVE_DELAY_0,
	PHY_RDDQS_DQ6_RISE_SLAVE_DELAY_0,
	PHY_RDDQS_DQ7_FALL_SLAVE_DELAY_0,
	PHY_RDDQS_DQ7_RISE_SLAVE_DELAY_0,
	PHY_RDDQS_DM_FALL_SLAVE_DELAY_0,
	PHY_RDDQS_DM_RISE_SLAVE_DELAY_0,
	PHY_WRITE_PATH_LAT_ADD_0,
	PHY_RDDQS_LATENCY_ADJUST_0,
	PHY_RDDQS_GATE_SLAVE_DELAY_0,
	PHY_DQ_TSEL_SELECT_1,
	PHY_DQS_TSEL_SELECT_1,
	PHY_LP4_RDLVL_PATT8_1,
	PHY_DQ_SWIZZLING_1,
	PHY_WRLVL_HARD1_DELAY_OBS_1,
	PHY_WRLVL_HARD0_DELAY_OBS_1,
	PHY_CLK_WRDQ1_SLAVE_DELAY_1,
	PHY_CLK_WRDQ0_SLAVE_DELAY_1,
	PHY_CLK_WRDQ3_SLAVE_DELAY_1,
	PHY_CLK_WRDQ2_SLAVE_DELAY_1,
	PHY_CLK_WRDQ5_SLAVE_DELAY_1,
	PHY_CLK_WRDQ4_SLAVE_DELAY_1,
	PHY_CLK_WRDQ7_SLAVE_DELAY_1,
	PHY_CLK_WRDQ6_SLAVE_DELAY_1,
	PHY_CLK_WRDQS_SLAVE_DELAY_1,
	PHY_CLK_WRDM_SLAVE_DELAY_1,
	PHY_RDDQ1_SLAVE_DELAY_1,
	PHY_RDDQ0_SLAVE_DELAY_1,
	PHY_RDDQ3_SLAVE_DELAY_1,
	PHY_RDDQ2_SLAVE_DELAY_1,
	PHY_RDDQ5_SLAVE_DELAY_1,
	PHY_RDDQ4_SLAVE_DELAY_1,
	PHY_RDDQ7_SLAVE_DELAY_1,
	PHY_RDDQ6_SLAVE_DELAY_1,
	PHY_RDDQS_DQ0_FALL_SLAVE_DELAY_1,
	PHY_RDDQS_DQ0_RISE_SLAVE_DELAY_1,
	PHY_RDDQS_DQ1_FALL_SLAVE_DELAY_1,
	PHY_RDDQS_DQ1_RISE_SLAVE_DELAY_1,
	PHY_RDDQS_DQ2_FALL_SLAVE_DELAY_1,
	PHY_RDDQS_DQ2_RISE_SLAVE_DELAY_1,
	PHY_RDDQS_DQ3_FALL_SLAVE_DELAY_1,
	PHY_RDDQS_DQ3_RISE_SLAVE_DELAY_1,
	PHY_RDDQS_DQ4_FALL_SLAVE_DELAY_1,
	PHY_RDDQS_DQ4_RISE_SLAVE_DELAY_1,
	PHY_RDDQS_DQ5_FALL_SLAVE_DELAY_1,
	PHY_RDDQS_DQ5_RISE_SLAVE_DELAY_1,
	PHY_RDDQS_DQ6_FALL_SLAVE_DELAY_1,
	PHY_RDDQS_DQ6_RISE_SLAVE_DELAY_1,
	PHY_RDDQS_DQ7_FALL_SLAVE_DELAY_1,
	PHY_RDDQS_DQ7_RISE_SLAVE_DELAY_1,
	PHY_RDDQS_DM_FALL_SLAVE_DELAY_1,
	PHY_RDDQS_DM_RISE_SLAVE_DELAY_1,
	PHY_WRITE_PATH_LAT_ADD_1,
	PHY_RDDQS_LATENCY_ADJUST_1,
	PHY_RDDQS_GATE_SLAVE_DELAY_1,
	PHY_DQ_TSEL_SELECT_2,
	PHY_DQS_TSEL_SELECT_2,
	PHY_LP4_RDLVL_PATT8_2,
	PHY_DQ_SWIZZLING_2,
	PHY_WRLVL_HARD1_DELAY_OBS_2,
	PHY_WRLVL_HARD0_DELAY_OBS_2,
	PHY_CLK_WRDQ1_SLAVE_DELAY_2,
	PHY_CLK_WRDQ0_SLAVE_DELAY_2,
	PHY_CLK_WRDQ3_SLAVE_DELAY_2,
	PHY_CLK_WRDQ2_SLAVE_DELAY_2,
	PHY_CLK_WRDQ5_SLAVE_DELAY_2,
	PHY_CLK_WRDQ4_SLAVE_DELAY_2,
	PHY_CLK_WRDQ7_SLAVE_DELAY_2,
	PHY_CLK_WRDQ6_SLAVE_DELAY_2,
	PHY_CLK_WRDQS_SLAVE_DELAY_2,
	PHY_CLK_WRDM_SLAVE_DELAY_2,
	PHY_RDDQ1_SLAVE_DELAY_2,
	PHY_RDDQ0_SLAVE_DELAY_2,
	PHY_RDDQ3_SLAVE_DELAY_2,
	PHY_RDDQ2_SLAVE_DELAY_2,
	PHY_RDDQ5_SLAVE_DELAY_2,
	PHY_RDDQ4_SLAVE_DELAY_2,
	PHY_RDDQ7_SLAVE_DELAY_2,
	PHY_RDDQ6_SLAVE_DELAY_2,
	PHY_RDDQS_DQ0_FALL_SLAVE_DELAY_2,
	PHY_RDDQS_DQ0_RISE_SLAVE_DELAY_2,
	PHY_RDDQS_DQ1_FALL_SLAVE_DELAY_2,
	PHY_RDDQS_DQ1_RISE_SLAVE_DELAY_2,
	PHY_RDDQS_DQ2_FALL_SLAVE_DELAY_2,
	PHY_RDDQS_DQ2_RISE_SLAVE_DELAY_2,
	PHY_RDDQS_DQ3_FALL_SLAVE_DELAY_2,
	PHY_RDDQS_DQ3_RISE_SLAVE_DELAY_2,
	PHY_RDDQS_DQ4_FALL_SLAVE_DELAY_2,
	PHY_RDDQS_DQ4_RISE_SLAVE_DELAY_2,
	PHY_RDDQS_DQ5_FALL_SLAVE_DELAY_2,
	PHY_RDDQS_DQ5_RISE_SLAVE_DELAY_2,
	PHY_RDDQS_DQ6_FALL_SLAVE_DELAY_2,
	PHY_RDDQS_DQ6_RISE_SLAVE_DELAY_2,
	PHY_RDDQS_DQ7_FALL_SLAVE_DELAY_2,
	PHY_RDDQS_DQ7_RISE_SLAVE_DELAY_2,
	PHY_RDDQS_DM_FALL_SLAVE_DELAY_2,
	PHY_RDDQS_DM_RISE_SLAVE_DELAY_2,
	PHY_WRITE_PATH_LAT_ADD_2,
	PHY_RDDQS_LATENCY_ADJUST_2,
	PHY_RDDQS_GATE_SLAVE_DELAY_2,
	PHY_DQ_TSEL_SELECT_3,
	PHY_DQS_TSEL_SELECT_3,
	PHY_LP4_RDLVL_PATT8_3,
	PHY_DQ_SWIZZLING_3,
	PHY_WRLVL_HARD1_DELAY_OBS_3,
	PHY_WRLVL_HARD0_DELAY_OBS_3,
	PHY_RDDQ1_SLAVE_DELAY_3,
	PHY_RDDQ0_SLAVE_DELAY_3,
	PHY_RDDQ3_SLAVE_DELAY_3,
	PHY_RDDQ2_SLAVE_DELAY_3,
	PHY_RDDQ5_SLAVE_DELAY_3,
	PHY_RDDQ4_SLAVE_DELAY_3,
	PHY_RDDQ7_SLAVE_DELAY_3,
	PHY_RDDQ6_SLAVE_DELAY_3,
	PHY_RDDQS_DQ0_FALL_SLAVE_DELAY_3,
	PHY_RDDQS_DQ0_RISE_SLAVE_DELAY_3,
	PHY_RDDQS_DQ1_FALL_SLAVE_DELAY_3,
	PHY_RDDQS_DQ1_RISE_SLAVE_DELAY_3,
	PHY_RDDQS_DQ2_FALL_SLAVE_DELAY_3,
	PHY_RDDQS_DQ2_RISE_SLAVE_DELAY_3,
	PHY_RDDQS_DQ3_FALL_SLAVE_DELAY_3,
	PHY_RDDQS_DQ3_RISE_SLAVE_DELAY_3,
	PHY_RDDQS_DQ4_FALL_SLAVE_DELAY_3,
	PHY_RDDQS_DQ4_RISE_SLAVE_DELAY_3,
	PHY_RDDQS_DQ5_FALL_SLAVE_DELAY_3,
	PHY_RDDQS_DQ5_RISE_SLAVE_DELAY_3,
	PHY_RDDQS_DQ6_FALL_SLAVE_DELAY_3,
	PHY_RDDQS_DQ6_RISE_SLAVE_DELAY_3,
	PHY_RDDQS_DQ7_FALL_SLAVE_DELAY_3,
	PHY_RDDQS_DQ7_RISE_SLAVE_DELAY_3,
	PHY_RDDQS_DM_FALL_SLAVE_DELAY_3,
	PHY_RDDQS_DM_RISE_SLAVE_DELAY_3,
	PHY_WRITE_PATH_LAT_ADD_3,
	PHY_RDDQS_LATENCY_ADJUST_3,
	PHY_RDDQS_GATE_SLAVE_DELAY_3,
	PHY_ADR_CALVL_SWIZZLE0_0_0,
	PHY_ADR_CALVL_SWIZZLE1_0_0,
	PHY_ADR_CALVL_SWIZZLE0_1_0,
	PHY_ADR_CALVL_DEVICE_MAP_0,
	PHY_ADR_CALVL_SWIZZLE1_1_0,
	PHY_ADR_ADDR_SEL_0,
	PHY_ADR0_CLK_WR_SLAVE_DELAY_0,
	PHY_ADR2_CLK_WR_SLAVE_DELAY_0,
	PHY_ADR1_CLK_WR_SLAVE_DELAY_0,
	PHY_ADR4_CLK_WR_SLAVE_DELAY_0,
	PHY_ADR3_CLK_WR_SLAVE_DELAY_0,
	PHY_ADR5_CLK_WR_SLAVE_DELAY_0,
	PHY_FREQ_SEL_INDEX,
	SC_PHY_MANUAL_UPDATE,
	PHY_GRP_SLAVE_DELAY_0,
	PHY_GRP_SLAVE_DELAY_2,
	PHY_GRP_SLAVE_DELAY_1,
	PHY_GRP_SLAVE_DELAY_3,
	PHY_PAD_ADDR_DRIVE,
	PHY_PAD_CLK_DRIVE,
	PHY_PAD_FDBK_TERM,
	PHY_PAD_DATA_TERM,
	PHY_PAD_DQS_TERM,
	PHY_PAD_ADDR_TERM,
	PHY_PAD_CLK_TERM,
	PHY_PAD_CKE_DRIVE,
	PHY_PAD_CKE_TERM,
	PHY_PAD_RST_DRIVE,
	PHY_PAD_RST_TERM,
	PHY_PAD_CS_DRIVE,
	PHY_PAD_CS_TERM,
	PHY_CAL_MODE_0,
	PHY_TST_CLK_PAD_CTRL2,
	PHY_CAL_START_0,
	PHY_CAL_CLEAR_0,
	PHY_CAL_CLK_SELECT_0,
	PHY_ADRCTL_MANUAL_UPDATE,
	PI_START,
	PI_CS_MAP,
	PI_SW_RST_N,
	PI_WDT_DISABLE,
	PI_WRLVL_EN,
	PI_RDLVL_GATE_EN,
	PI_RDLVL_EN,
	PI_RDLVL_PATTERN_START,
	PI_CALVL_EN,
	PI_CALVL_CS_MAP,
	PI_WDQLVL_EN,
	PI_INT_STATUS
};

uint32_t ddr_phy_reg_read(uint32_t ch, uint32_t reg);
void ddr_phy_reg_write(uint32_t ch, uint16_t reg, uint32_t data);
uint32_t ddr_phy_reg_rawread(uint32_t ch, uint32_t reg);
void ddr_phy_reg_rawwrite(uint32_t ch, uint16_t reg, uint32_t data);
void bl2_phy_init(void);

#endif	/* BL2_PHY_INIT_H__ */
