/*
 * Copyright (c) 2021 EPAM Systems Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of ARM nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef RCAR_SCMI_RESOURCES_H
#define RCAR_SCMI_RESOURCES_H

enum rcar_scmi_devid {
	RCAR_SCMIDEV_EAVB,	/*  0 */
	RCAR_SCMIDEV_HDMI0,	/*  1 */
	RCAR_SCMIDEV_HDMI1,	/*  2 */
	RCAR_SCMIDEV_I2C0,	/*  3 */
	RCAR_SCMIDEV_I2C1,	/*  4 */
	RCAR_SCMIDEV_I2C2,	/*  5 */
	RCAR_SCMIDEV_I2C3,	/*  6 */
	RCAR_SCMIDEV_I2C4,	/*  7 */
	RCAR_SCMIDEV_XHCI0,	/*  8 */
	RCAR_SCMIDEV_OHCI0,	/*  9 */
	RCAR_SCMIDEV_EHCI0,	/* 10 */
	RCAR_SCMIDEV_OHCI1,	/* 11 */
	RCAR_SCMIDEV_EHCI1,	/* 12 */
	RCAR_SCMIDEV_USB_DMAC0,	/* 13 */
	RCAR_SCMIDEV_USB_DMAC1,	/* 14 */
	RCAR_SCMIDEV_USB_DMAC2,	/* 15 */
	RCAR_SCMIDEV_USB_DMAC3,	/* 16 */
	RCAR_SCMIDEV_USB2_PHY0,	/* 17 */
	RCAR_SCMIDEV_USB2_PHY1,	/* 18 */
	RCAR_SCMIDEV_HSUSB,	/* 19 */
	RCAR_SCMIDEV_SOUND,	/* 20 */
	RCAR_SCMIDEV_AUDMA0,	/* 21 */
	RCAR_SCMIDEV_AUDMA1,	/* 22 */
	RCAR_SCMIDEV_GPIO0,	/* 23 */
	RCAR_SCMIDEV_GPIO1,	/* 24 */
	RCAR_SCMIDEV_GPIO2,	/* 25 */
	RCAR_SCMIDEV_GPIO3,	/* 26 */
	RCAR_SCMIDEV_GPIO4,	/* 27 */
	RCAR_SCMIDEV_GPIO5,	/* 28 */
	RCAR_SCMIDEV_GPIO6,	/* 29 */
	RCAR_SCMIDEV_GPIO7,	/* 30 */
	RCAR_SCMIDEV_PINCTRL,	/* 31 */
	RCAR_SCMIDEV_CAN0,	/* 32 */
	RCAR_SCMIDEV_CAN1,	/* 33 */
	RCAR_SCMIDEV_CANFD,	/* 34 */
	RCAR_SCMIDEV_DRIF0,	/* 35 */
	RCAR_SCMIDEV_DRIF1,	/* 36 */
	RCAR_SCMIDEV_DRIF2,	/* 37 */
	RCAR_SCMIDEV_DRIF3,	/* 38 */
	RCAR_SCMIDEV_DU,	/* 39 */
	RCAR_SCMIDEV_HSCIF0,	/* 40 */
	RCAR_SCMIDEV_HSCIF1,	/* 41 */
	RCAR_SCMIDEV_HSCIF2,	/* 42 */
	RCAR_SCMIDEV_HSCIF3,	/* 43 */
	RCAR_SCMIDEV_HSCIF4,	/* 44 */
	RCAR_SCMIDEV_I2C5,	/* 45 */
	RCAR_SCMIDEV_I2C6,	/* 46 */
	RCAR_SCMIDEV_I2C_DVFS,	/* 47 */
	RCAR_SCMIDEV_MLB,	/* 48 */
	RCAR_SCMIDEV_MSIOF0,	/* 49 */
	RCAR_SCMIDEV_MSIOF1,	/* 50 */
	RCAR_SCMIDEV_MSIOF2,	/* 51 */
	RCAR_SCMIDEV_MSIOF3,	/* 52 */
	RCAR_SCMIDEV_PWM0,	/* 53 */
	RCAR_SCMIDEV_PWM1,	/* 54 */
	RCAR_SCMIDEV_PWM2,	/* 55 */
	RCAR_SCMIDEV_PWM3,	/* 56 */
	RCAR_SCMIDEV_PWM4,	/* 57 */
	RCAR_SCMIDEV_PWM5,	/* 58 */
	RCAR_SCMIDEV_PWM6,	/* 59 */
	RCAR_SCMIDEV_SATA,	/* 60 */
	RCAR_SCMIDEV_SCIF0,	/* 61 */
	RCAR_SCMIDEV_SCIF1,	/* 62 */
	RCAR_SCMIDEV_SCIF2,	/* 63 */
	RCAR_SCMIDEV_SCIF3,	/* 64 */
	RCAR_SCMIDEV_SCIF4,	/* 65 */
	RCAR_SCMIDEV_SCIF5,	/* 66 */
	RCAR_SCMIDEV_SDHI0,	/* 67 */
	RCAR_SCMIDEV_SDHI1,	/* 68 */
	RCAR_SCMIDEV_SDHI2,	/* 69 */
	RCAR_SCMIDEV_SDHI3,	/* 70 */
	RCAR_SCMIDEV_SSI,	/* 71 */
	RCAR_SCMIDEV_TMU,	/* 72 */
	RCAR_SCMIDEV_TPU,	/* 73 */
	RCAR_SCMIDEV_USB0,	/* 74 */
	RCAR_SCMIDEV_USB1,	/* 75 */
	RCAR_SCMIDEV_USB2,	/* 76 */
	RCAR_SCMIDEV_USB3,	/* 77 */
	RCAR_SCMIDEV_VIN4,	/* 78 */
	RCAR_SCMIDEV_VIN5,	/* 79 */

	RCAR_SCMIDEV_MAX
};

enum rcar_scmi_rst_offset {
	RCAR_SCMIRST_EAVB,	/*  0*/
	RCAR_SCMIRST_HDMI0,	/*  1 */
	RCAR_SCMIRST_HDMI1,	/*  2 */
	RCAR_SCMIRST_I2C0,	/*  3 */
	RCAR_SCMIRST_I2C1,	/*  4 */
	RCAR_SCMIRST_I2C2,	/*  5 */
	RCAR_SCMIRST_I2C3,	/*  6 */
	RCAR_SCMIRST_I2C4,	/*  7 */
	RCAR_SCMIRST_XHCI0,	/*  8 */
	RCAR_SCMIRST_USB2_01,	/*  9 */
	RCAR_SCMIRST_USB2_02,	/* 10 */
	RCAR_SCMIRST_USB2_1,	/* 11 */
	RCAR_SCMIRST_USB_DMAC0,	/* 12 */
	RCAR_SCMIRST_USB_DMAC1,	/* 13 */
	RCAR_SCMIRST_USB_DMAC2,	/* 14 */
	RCAR_SCMIRST_USB_DMAC3,	/* 15 */
	RCAR_SCMIRST_SSI,	/* 16 */
	RCAR_SCMIRST_SSI9,	/* 17 */
	RCAR_SCMIRST_SSI8,	/* 18 */
	RCAR_SCMIRST_SSI7,	/* 19 */
	RCAR_SCMIRST_SSI6,	/* 20 */
	RCAR_SCMIRST_SSI5,	/* 21 */
	RCAR_SCMIRST_SSI4,	/* 22 */
	RCAR_SCMIRST_SSI3,	/* 23 */
	RCAR_SCMIRST_SSI2,	/* 24 */
	RCAR_SCMIRST_SSI1,	/* 25 */
	RCAR_SCMIRST_SSI0,	/* 26 */
	RCAR_SCMIRST_AUDMAC1,	/* 27 */
	RCAR_SCMIRST_AUDMAC0,	/* 28 */
	RCAR_SCMIRST_MAX
};

enum rcar_scmi_clk {
	RCAR_SCMICLK_EAVB,	/*  0 */
	RCAR_SCMICLK_XHCI0,	/*  1 */
	RCAR_SCMICLK_EHCI0,	/*  2 */
	RCAR_SCMICLK_HSUSB,	/*  3 */
	RCAR_SCMICLK_EHCI1,	/*  4 */
	RCAR_SCMICLK_USB_DMAC0,	/*  5 */
	RCAR_SCMICLK_USB_DMAC1,	/*  6 */
	RCAR_SCMICLK_USB_DMAC30,/*  7 */
	RCAR_SCMICLK_USB_DMAC31,/*  8 */
	RCAR_SCMICLK_SSI_ALL,	/*  9 */
	RCAR_SCMICLK_SSI9,	/* 10 */
	RCAR_SCMICLK_SSI8,	/* 11 */
	RCAR_SCMICLK_SSI7,	/* 12 */
	RCAR_SCMICLK_SSI6,	/* 13 */
	RCAR_SCMICLK_SSI5,	/* 14 */
	RCAR_SCMICLK_SSI4,	/* 15 */
	RCAR_SCMICLK_SSI3,	/* 16 */
	RCAR_SCMICLK_SSI2,	/* 17 */
	RCAR_SCMICLK_SSI1,	/* 18 */
	RCAR_SCMICLK_SSI0,	/* 19 */
	RCAR_SCMICLK_SCU_ALL,	/* 20 */
	RCAR_SCMICLK_SCU_DVC1,	/* 21 */
	RCAR_SCMICLK_SCU_DVC0,	/* 22 */
	RCAR_SCMICLK_SCU_MIX1,	/* 23 */
	RCAR_SCMICLK_SCU_MIX0,	/* 24 */
	RCAR_SCMICLK_SCU_SRC9,	/* 25 */
	RCAR_SCMICLK_SCU_SRC8,	/* 26 */
	RCAR_SCMICLK_SCU_SRC7,	/* 27 */
	RCAR_SCMICLK_SCU_SRC6,	/* 28 */
	RCAR_SCMICLK_SCU_SRC5,	/* 29 */
	RCAR_SCMICLK_SCU_SRC4,	/* 30 */
	RCAR_SCMICLK_SCU_SRC3,	/* 31 */
	RCAR_SCMICLK_SCU_SRC2,	/* 32 */
	RCAR_SCMICLK_SCU_SRC1,	/* 33 */
	RCAR_SCMICLK_SCU_SRC0,	/* 34 */
	RCAR_SCMICLK_AUDMAC1,	/* 35 */
	RCAR_SCMICLK_AUDMAC0,	/* 36 */
	RCAR_SCMICLK_HDMI,
	RCAR_SCMICLK_HDMI0,
	RCAR_SCMICLK_HDMI1,
	RCAR_CLK_EXTAL,
	RCAR_CLK_MAIN,
	RCAR_CLK_PLL1,
	RCAR_CLK_PLL1D2,
	RCAR_CLK_S0,
	RCAR_CLK_S1,
	RCAR_CLK_S3,
	RCAR_CLK_S0D6,
	RCAR_CLK_S1D2,
	RCAR_CLK_S3D1,
	RCAR_CLK_S3D2,
	RCAR_CLK_S3D4,
	RCAR_CLK_MAX,
	RCAR_SCMICLK_MAX = RCAR_SCMICLK_HDMI /* end of SCMI exported clocks */
};

enum rcar_scmi_pinctrl {
	RCAR_SCMIPIN_EAVB,        /* 0 */
	RCAR_SCMIPIN_I2C0,        /* 1 */
	RCAR_SCMIPIN_I2C1,        /* 2 */
	RCAR_SCMIPIN_I2C2,        /* 3 */
	RCAR_SCMIPIN_I2C3,        /* 4 */
	RCAR_SCMIPIN_I2C4,        /* 5 */
	RCAR_SCMIPIN_XHCI0,       /* 6 */
	RCAR_SCMIPIN_OHCI0,       /* 7 */
	RCAR_SCMIPIN_EHCI0,       /* 8 */
	RCAR_SCMIPIN_OHCI1,       /* 9 */
	RCAR_SCMIPIN_EHCI1,       /* 10 */
	RCAR_SCMIPIN_USB_DMAC0,   /* 11 */
	RCAR_SCMIPIN_USB_DMAC1,   /* 12 */
	RCAR_SCMIPIN_USB_DMAC2,   /* 13 */
	RCAR_SCMIPIN_USB_DMAC3,   /* 14 */
	RCAR_SCMIPIN_USB2_PHY0,   /* 15 */
	RCAR_SCMIPIN_USB2_PHY1,   /* 16 */
	RCAR_SCMIPIN_USB_HSUSB,   /* 17 */
	RCAR_SCMIPIN_SOUND,       /* 18 */
	RCAR_SCMIPIN_AUDMA0,      /* 19 */
	RCAR_SCMIPIN_AUDMA1,      /* 20 */
	RCAR_SCMIPIN_GPIO0,       /* 21 */
	RCAR_SCMIPIN_GPIO1,       /* 22 */
	RCAR_SCMIPIN_GPIO2,       /* 23 */
	RCAR_SCMIPIN_GPIO3,       /* 24 */
	RCAR_SCMIPIN_GPIO4,       /* 25 */
	RCAR_SCMIPIN_GPIO5,       /* 26 */
	RCAR_SCMIPIN_GPIO6,       /* 27 */
	RCAR_SCMIPIN_GPIO7,       /* 28 */
	RCAR_SCMIPIN_PINCTRL,     /* 29 */
	RCAR_SCMIPIN_CAN0,        /* 30 */
	RCAR_SCMIPIN_CAN1,        /* 31 */
	RCAR_SCMIPIN_CANFD,       /* 32 */
	RCAR_SCMIPIN_DRIF0,       /* 33 */
	RCAR_SCMIPIN_DRIF1,       /* 34 */
	RCAR_SCMIPIN_DRIF2,       /* 35 */
	RCAR_SCMIPIN_DRIF3,       /* 36 */
	RCAR_SCMIPIN_DU,          /* 37 */
	RCAR_SCMIPIN_HSCIF0,      /* 38 */
	RCAR_SCMIPIN_HSCIF1,      /* 39 */
	RCAR_SCMIPIN_HSCIF2,      /* 40 */
	RCAR_SCMIPIN_HSCIF3,      /* 41 */
	RCAR_SCMIPIN_HSCIF4,      /* 42 */
	RCAR_SCMIPIN_I2C5,        /* 43 */
	RCAR_SCMIPIN_I2C6,        /* 44 */
	RCAR_SCMIPIN_I2C_DVFS,    /* 45 */
	RCAR_SCMIPIN_MLB,         /* 46 */
	RCAR_SCMIPIN_MSIOF0,      /* 47 */
	RCAR_SCMIPIN_MSIOF1,      /* 48 */
	RCAR_SCMIPIN_MSIOF2,      /* 49 */
	RCAR_SCMIPIN_MSIOF3,      /* 50 */
	RCAR_SCMIPIN_PWM0,        /* 51 */
	RCAR_SCMIPIN_PWM1,        /* 52 */
	RCAR_SCMIPIN_PWM2,        /* 53 */
	RCAR_SCMIPIN_PWM3,        /* 54 */
	RCAR_SCMIPIN_PWM4,        /* 55 */
	RCAR_SCMIPIN_PWM5,        /* 56 */
	RCAR_SCMIPIN_PWM6,        /* 57 */
	RCAR_SCMIPIN_SATA,        /* 58 */
	RCAR_SCMIPIN_SCIF0,       /* 59 */
	RCAR_SCMIPIN_SCIF1,       /* 60 */
	RCAR_SCMIPIN_SCIF2,       /* 61 */
	RCAR_SCMIPIN_SCIF3,       /* 62 */
	RCAR_SCMIPIN_SCIF4,       /* 63 */
	RCAR_SCMIPIN_SCIF5,       /* 64 */
	RCAR_SCMIPIN_SDHI0,       /* 65 */
	RCAR_SCMIPIN_SDHI1,       /* 66 */
	RCAR_SCMIPIN_SDHI2,       /* 67 */
	RCAR_SCMIPIN_SDHI3,       /* 68 */
	RCAR_SCMIPIN_SSI,         /* 69 */
	RCAR_SCMIPIN_TMU,         /* 70 */
	RCAR_SCMIPIN_TPU,         /* 71 */
	RCAR_SCMIPIN_USB0,        /* 72 */
	RCAR_SCMIPIN_USB1,        /* 73 */
	RCAR_SCMIPIN_USB2,        /* 74 */
	RCAR_SCMIPIN_USB3,        /* 75 */
	RCAR_SCMIPIN_VIN4,        /* 76 */
	RCAR_SCMIPIN_VIN5,        /* 77 */

	RCAR_PINCTRL_MAX, /* end of SCMI exported pinctrl regs */
};

extern const struct scmi_device rcar_devices[RCAR_SCMIDEV_MAX];
extern struct scmi_clk rcar_clocks[RCAR_CLK_MAX];
extern struct scmi_reset rcar_resets[RCAR_SCMIRST_MAX];
extern struct scmi_pinctrl rcar_pinctrl[RCAR_PINCTRL_MAX];

#endif /* RCAR_SCMI_RESOURCES_H */
